//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string LabelForAbout {
            get {
                return ResourceManager.GetString("LabelForAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Addresses ähnelt.
        /// </summary>
        public static string LabelForAddresses {
            get {
                return ResourceManager.GetString("LabelForAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apllicaltion Uses ähnelt.
        /// </summary>
        public static string LabelForApplicationUses {
            get {
                return ResourceManager.GetString("LabelForApplicationUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die at ähnelt.
        /// </summary>
        public static string LabelForAt {
            get {
                return ResourceManager.GetString("LabelForAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Books ähnelt.
        /// </summary>
        public static string LabelForBooks {
            get {
                return ResourceManager.GetString("LabelForBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Branches ähnelt.
        /// </summary>
        public static string LabelForBranches {
            get {
                return ResourceManager.GetString("LabelForBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Business ähnelt.
        /// </summary>
        public static string LabelForBusiness {
            get {
                return ResourceManager.GetString("LabelForBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collections ähnelt.
        /// </summary>
        public static string LabelForCollections {
            get {
                return ResourceManager.GetString("LabelForCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        public static string LabelForContact {
            get {
                return ResourceManager.GetString("LabelForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contributing Fields ähnelt.
        /// </summary>
        public static string LabelForContributingFields {
            get {
                return ResourceManager.GetString("LabelForContributingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string LabelForData {
            get {
                return ResourceManager.GetString("LabelForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Degree of maturity ähnelt.
        /// </summary>
        public static string LabelForDegreeOfMaturity {
            get {
                return ResourceManager.GetString("LabelForDegreeOfMaturity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Influantial People ähnelt.
        /// </summary>
        public static string LabelForInfluentialPeople {
            get {
                return ResourceManager.GetString("LabelForInfluentialPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sources ähnelt.
        /// </summary>
        public static string LabelForInfoSources {
            get {
                return ResourceManager.GetString("LabelForInfoSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Journals ähnelt.
        /// </summary>
        public static string LabelForJournals {
            get {
                return ResourceManager.GetString("LabelForJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learn More ähnelt.
        /// </summary>
        public static string LabelForLearnMore {
            get {
                return ResourceManager.GetString("LabelForLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modes of Locomotion ähnelt.
        /// </summary>
        public static string LabelForModesOfLocomotion {
            get {
                return ResourceManager.GetString("LabelForModesOfLocomotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New entry ähnelt.
        /// </summary>
        public static string LabelForNewEntry {
            get {
                return ResourceManager.GetString("LabelForNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Newspapers ähnelt.
        /// </summary>
        public static string LabelForNewspapers {
            get {
                return ResourceManager.GetString("LabelForNewspapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Official Statements ähnelt.
        /// </summary>
        public static string LabelForOfficialStatements {
            get {
                return ResourceManager.GetString("LabelForOfficialStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overview ähnelt.
        /// </summary>
        public static string LabelForOverview {
            get {
                return ResourceManager.GetString("LabelForOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die p. ähnelt.
        /// </summary>
        public static string LabelForPagesAbbreviation {
            get {
                return ResourceManager.GetString("LabelForPagesAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string LabelForProperties {
            get {
                return ResourceManager.GetString("LabelForProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property Category ähnelt.
        /// </summary>
        public static string LabelForPropertyCategory {
            get {
                return ResourceManager.GetString("LabelForPropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   ähnelt.
        /// </summary>
        public static string LabelForPublisherAbbreviation {
            get {
                return ResourceManager.GetString("LabelForPublisherAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robot ähnelt.
        /// </summary>
        public static string LabelForRobot {
            get {
                return ResourceManager.GetString("LabelForRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robotics Companies ähnelt.
        /// </summary>
        public static string LabelForRoboticsCompanies {
            get {
                return ResourceManager.GetString("LabelForRoboticsCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robotics Competitions ähnelt.
        /// </summary>
        public static string LabelForRoboticsCompetition {
            get {
                return ResourceManager.GetString("LabelForRoboticsCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robotics Competitions ähnelt.
        /// </summary>
        public static string LabelForRoboticsCompetitions {
            get {
                return ResourceManager.GetString("LabelForRoboticsCompetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robotics Components And Design Features ähnelt.
        /// </summary>
        public static string LabelForRoboticsComponentsAndDesignFeatures {
            get {
                return ResourceManager.GetString("LabelForRoboticsComponentsAndDesignFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Development and Development Tools ähnelt.
        /// </summary>
        public static string LabelForRoboticsDevelopmentAndDevelopmentTools {
            get {
                return ResourceManager.GetString("LabelForRoboticsDevelopmentAndDevelopmentTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Organization ähnelt.
        /// </summary>
        public static string LabelForRoboticsOrganization {
            get {
                return ResourceManager.GetString("LabelForRoboticsOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robotics Organizations ähnelt.
        /// </summary>
        public static string LabelForRoboticsOrganizations {
            get {
                return ResourceManager.GetString("LabelForRoboticsOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robotic Principles ähnelt.
        /// </summary>
        public static string LabelForRoboticsPrinciples {
            get {
                return ResourceManager.GetString("LabelForRoboticsPrinciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Robots ähnelt.
        /// </summary>
        public static string LabelForRobots {
            get {
                return ResourceManager.GetString("LabelForRobots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Series ähnelt.
        /// </summary>
        public static string LabelForSeries {
            get {
                return ResourceManager.GetString("LabelForSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Types ähnelt.
        /// </summary>
        public static string LabelForTypes {
            get {
                return ResourceManager.GetString("LabelForTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unpublished ähnelt.
        /// </summary>
        public static string LabelForUnpublished {
            get {
                return ResourceManager.GetString("LabelForUnpublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Websites ähnelt.
        /// </summary>
        public static string LabelForWebsites {
            get {
                return ResourceManager.GetString("LabelForWebsites", resourceCulture);
            }
        }
    }
}
